/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';




export namespace Components {

  interface WineFeaturedProducts {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface WineFeaturedProductsAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WineFeaturedProducts': Components.WineFeaturedProducts;
  }

  interface StencilIntrinsicElements {
    'wine-featured-products': Components.WineFeaturedProductsAttributes;
  }


  interface HTMLWineFeaturedProductsElement extends Components.WineFeaturedProducts, HTMLStencilElement {}
  var HTMLWineFeaturedProductsElement: {
    prototype: HTMLWineFeaturedProductsElement;
    new (): HTMLWineFeaturedProductsElement;
  };

  interface HTMLElementTagNameMap {
    'wine-featured-products': HTMLWineFeaturedProductsElement
  }

  interface ElementTagNameMap {
    'wine-featured-products': HTMLWineFeaturedProductsElement;
  }


}
